apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapi-deployment
  labels:
    app: login-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-api
  template:
    metadata:
      labels:
        app: login-api
    spec:
      containers:
      - name: login-api
        image: xwindwolfx/login-api:latest
        ports:
        - containerPort: 5000